### ISSUE TITLE
Add Support for Apple Silicon (Arm64)

### ISSUE THREAD

**Issue by ihidchaos** [andestech/Andes-Development-Kit#1]
Please add support for Apple Silicon (Arm64), which currently only supports x86 architecture [nds-openocd_adapters](https://github.com/andestech/nds-openocd_adapters/tree/fc00c2c41eedb2c89423f27bdfb3bc2e8bd201d2/libusb-AICE-driver).

**Comment by twpedersen** [comment]
any hope for AST builds for macos?
